language: java
sudo: true
dist: trusty
jdk:
  - openjdk8
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
before_install:
  - sudo mysql -e 'CREATE DATABASE renfei;'
  - mysql -u root --default-character-set=utf8 renfei < db/renfei.sql
  - mysql_upgrade -u root
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo apt-get install -y curl
  - sudo curl --silent --location https://rpm.nodesource.com/setup_10.x | bash -
  - sudo apt-get install -y python-software-properties
  - sudo apt-get install -y nodejs
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn clean cobertura:cobertura coveralls:report