language: java
sudo: true
jdk:
  - openjdk8
services:
  - mysql
script: "mvn cobertura:cobertura"
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - mysql -e 'CREATE DATABASE renfei; use renfei; source ./db/renfei.sql'
  - sudo service mysql restart

