language: java
sudo: true
dist: trusty
jdk:
  - openjdk8
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
before_install:
  - sudo mysql -e 'CREATE DATABASE renfei;'
  - mysql -u root --default-character-set=utf8 renfei < db/renfei.sql
  - sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO root@'%' IDENTIFIED BY '.'; FLUSH PRIVILEGES;"
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn clean cobertura:cobertura coveralls:report