version: "3"
services:
  mysql:
    container_name: mysql
    build:
      context: ../
      dockerfile: docker/mysql-dockerfile
    restart: always
    volumes:
      - ${DIR}/mysql/data/:/var/lib/mysql/  #映射mysql的数据目录到宿主机，保存数据
      - ${DIR}/mysql/conf/my.cnf:/etc/my.cnf #把mysql的配置文件映射到容器的相应目录
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_HOST=%
    command: mysqld -uroot --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    expose:
      - 6379
    volumes:
      - ${DIR}/redis/conf:/usr/local/etc/redis
      - ${DIR}/redis/data:/data
    command:
      redis-server
  nginx:
    container_name: nginx
    build:
      context: ../
      dockerfile: docker/nginx-dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${DIR}/nginx/webserver:/webserver
      - ${DIR}/nginx/conf/:/usr/local/nginx/conf/           #映射nginx的配置文件到容器里
      - ${DIR}/nginx/logs/:/usr/local/nginx/logs/
      - ${DIR}/nginx/html/:/var/share/nginx/html/                     #映射nginx的网页目录到容器里
    links:
      - app                                               #连接 tomcat镜像
  app:
    container_name: app
    restart: always
    iamge: java:8
    working_dir: /app
    volumes:
      - ${DIR}/app:/app
      - ${DIR}/log:/opt/RenFeiNet/log
      - ~/.m2:/root/.m2
    expose:
      - 8091
    depends_on:
      - redis
      - mysql
    entrypoint: java -jar /app/web.jar