spring:
  datasource:
    url: jdbc:mysql://mysql/renfei?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8
    username: ENC(qsdpai1H179WuvJVu3CfYQ==)
    password: ENC(XXjERRQgq7TSsMbaxThQcg==)
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.zoho.com
    port: 465
    username: noreply@email.renfei.net
    password: [yourpassword]
    protocol: smtp
    default-encoding: UTF-8
    eeply-to: i@renfei.net
    properties:
      mail.smtp.localhost: email.renfei.net
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc
#jasypt加密的密匙
jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7
renfei:
  totpseed: wHwswcyAsxniH7a9Aifb6TqpwP4LAiF3YFVFJa3YiVoHzTENqY7QzLm9rko28N9sKhVBczcHQxKWXDhGQ92XvFCsjVQvLty28aDHCdJsMrv2kFTLFAKcCWmT6tg6ctdN
  jwtprivatekey: MF8CAQAwEAYHKoZIzj0CAQYFK4EEACMESDBGAgEBBEGzzx+yA0Zr2iubNgGp+PVggzlYXCGDxwejH8Qqsj7kus01A84K60P7tFz6klplVoPBiAb4iAwHQWLDJzFdvJ1guQ==
  jwtpublickey: MIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQB/FzIghjaFdeMUMbQdNLTiN6B3yWMoVLgInfWG6Xkpb/gwN9K0NBnv5jDnvoqe00GmjMJvELkyKViuBYZFaj6vI4APQSInAAGKmQcu+80QA5a8vHCtnLeqNiGZuEWQ5oVeXBnTKGhqUYTIdbBcAliEeFheaRjH7aQtPQZeO9+PhcpQhk=
  jwtaeskey: kjdur7gjnd7uj3gi
  GREEN_REGION_ID: cn-shanghai
  ALIYUN_ACCESS_KEY_ID: XXXXX
  ALIYUN_ACCESS_KEY_SECRET: XXXXX
  ALIYUN_OSS_ENDPOINT: http://oss-cn-beijing.aliyuncs.com
  ALIYUN_OSS_BUCKENAME: renfei
  BAIDU_ZIYUAN_SITE: https://www.renfei.net
  BAIDU_ZIYUAN_TOKEN: token
  BAIDU_ZIYUAN_MOBILE_APPID: appid
  BAIDU_ZIYUAN_MOBILE_TOKEN: token
  WECHAT_APP_ID: test
  WECHAT_APP_SECRET: test
  WECHAT_TOKEN: test
  WECHAT_EncodingAESKey: test