spring:
  datasource:
    url: jdbc:mysql://localhost/csscshow?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8
    username: ENC(qsdpai1H179WuvJVu3CfYQ==)
    password: ENC(XXjERRQgq7TSsMbaxThQcg==)
#    password: 6W8.BqxY
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.exmail.qq.com
    port: 465
    username: no-reply@renfei.net
    password: [yourpassword]
    protocol: smtp
    default-encoding: UTF-8
    eeply-to: i@renfei.net
    properties:
      mail.smtp.localhost: renfei.net
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
#jasypt加密的密匙
jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7
renfei:
  totpseed: wHwswcyAsxniH7a9Aifb6TqpwP4LAiF3YFVFJa3YiVoHzTENqY7QzLm9rko28N9sKhVBczcHQxKWXDhGQ92XvFCsjVQvLty28aDHCdJsMrv2kFTLFAKcCWmT6tg6ctdN
  jwtprivatekey: MF8CAQAwEAYHKoZIzj0CAQYFK4EEACMESDBGAgEBBEGzzx+yA0Zr2iubNgGp+PVggzlYXCGDxwejH8Qqsj7kus01A84K60P7tFz6klplVoPBiAb4iAwHQWLDJzFdvJ1guQ==
  jwtpublickey: MIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQB/FzIghjaFdeMUMbQdNLTiN6B3yWMoVLgInfWG6Xkpb/gwN9K0NBnv5jDnvoqe00GmjMJvELkyKViuBYZFaj6vI4APQSInAAGKmQcu+80QA5a8vHCtnLeqNiGZuEWQ5oVeXBnTKGhqUYTIdbBcAliEeFheaRjH7aQtPQZeO9+PhcpQhk=
  jwtaeskey: kjdur7gjnd7uj3gi
  GREEN_REGION_ID: cn-beijing
  ALIYUN_ACCESS_KEY_ID: LTAI90UjvXDiQGKB
  ALIYUN_ACCESS_KEY_SECRET: [yourpassword]
