spring:
  datasource:
    url: jdbc:mysql://localhost/renfei?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.zoho.com
    port: 465
    username: noreply@email.renfei.net
    password: [password]
    protocol: smtp
    default-encoding: UTF-8
    eeply-to: i@renfei.net
    properties:
      mail.smtp.localhost: email.renfei.net
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
